'use strict';
const content=require('../source/portal/learning-content');
exports.config={transaction:false};
exports.up=async function(db){
 const [database]=await db.raw('SELECT DATABASE() AS name');if(database[0].name!=='mini_hrms')throw new Error('Portal migrations require mini_hrms.');
 const create=async(name,build)=>{if(!(await db.schema.hasTable(name)))await db.schema.createTable(name,build);};
 await create('portal_catalog',t=>{t.increments('id');t.string('kind',32).notNullable();t.string('code',80).notNullable();t.string('name',150).notNullable();t.text('description');t.json('payload');t.boolean('status').notNullable().defaultTo(1);t.integer('createdBy').nullable().references('userId').inTable('employees');t.timestamp('createdAt').defaultTo(db.fn.now());t.timestamp('updatedAt').nullable();t.unique(['kind','code']);});
 await create('portal_requests',t=>{t.increments('id');t.integer('userId').notNullable().references('userId').inTable('employees');t.string('name',150).notNullable();t.string('kind',32).notNullable();t.text('description').notNullable();t.date('startDate').nullable();t.date('endDate').nullable();t.string('status',20).notNullable().defaultTo('pending');t.integer('reviewedBy').nullable().references('userId').inTable('employees');t.timestamp('createdAt').defaultTo(db.fn.now());t.timestamp('updatedAt').nullable();t.index(['userId','status']);});
 await create('portal_notifications',t=>{t.increments('id');t.string('name',150).notNullable();t.text('description').notNullable();t.string('audience',20).notNullable().defaultTo('all');t.integer('recipientId').nullable().references('userId').inTable('employees');t.integer('createdBy').nullable().references('userId').inTable('employees');t.timestamp('createdAt').defaultTo(db.fn.now());t.index(['recipientId','createdAt']);});
 await create('portal_sessions',t=>{t.string('id',64).primary();t.integer('userId').notNullable().references('userId').inTable('employees');t.string('loginKind',20).notNullable();t.integer('auditId').nullable();t.timestamp('expiresAt').notNullable();t.timestamp('revokedAt').nullable();t.timestamp('createdAt').defaultTo(db.fn.now());t.index(['userId','expiresAt']);});
 await create('portal_password_resets',t=>{t.string('id',64).primary();t.integer('userId').nullable().references('userId').inTable('employees');t.string('codeHash',64).notNullable();t.integer('attempts').notNullable().defaultTo(0);t.timestamp('expiresAt').notNullable();t.timestamp('consumedAt').nullable();t.timestamp('createdAt').defaultTo(db.fn.now());t.index(['userId','expiresAt']);});
 await create('portal_rate_limits',t=>{t.string('id',64).primary();t.integer('hits').notNullable();t.timestamp('windowEnds').notNullable();});
 await create('portal_learning_items',t=>{t.increments('id');t.string('slug',100).notNullable().unique();t.string('topic',32).notNullable();t.string('kind',20).notNullable();t.string('title',200).notNullable();t.text('body');t.text('example');t.string('source',500);t.integer('minutes').defaultTo(4);t.integer('position').defaultTo(0);t.json('data');t.index(['topic','kind']);});
 await create('portal_learning_progress',t=>{t.increments('id');t.integer('userId').notNullable().references('userId').inTable('employees');t.integer('itemId').unsigned().notNullable().references('id').inTable('portal_learning_items');t.boolean('completed').notNullable().defaultTo(0);t.timestamp('updatedAt').defaultTo(db.fn.now());t.unique(['userId','itemId']);});
 await create('portal_quiz_attempts',t=>{t.increments('id');t.integer('userId').notNullable().references('userId').inTable('employees');t.integer('score').notNullable();t.integer('total').notNullable();t.json('feedback');t.timestamp('createdAt').defaultTo(db.fn.now());t.index(['userId','createdAt']);});
 const permissions=[['employees:read','Read employee directories and profiles'],['employees:write','Create and update employees'],['settings:write','Manage workspace configuration'],['requests:review','Review employee requests'],['notifications:write','Publish in-app announcements']];
 for(const [code,description] of permissions){if(!(await db('portal_catalog').where({kind:'permissions',code}).first()))await db('portal_catalog').insert({kind:'permissions',code,name:code,description,payload:'{}',status:1});}
 const roles=[['admin','Administrator',permissions.map(p=>p[0])],['employee','Employee',[]],['hr','People operations',['employees:read','employees:write','requests:review','notifications:write']],['rm','Reporting manager',['employees:read','requests:review']],['pm','Project manager',['employees:read']],['fm','Finance manager',[]],['ceo','Chief executive',['employees:read']],['director','Director',['employees:read']]];
 for(const [code,name,allowed] of roles){if(!(await db('portal_catalog').where({kind:'roles',code}).first()))await db('portal_catalog').insert({kind:'roles',code,name,description:'Workspace role',payload:JSON.stringify({permissions:allowed.join(',')}),status:1});}
 const records=[...content.lessons.map((l,i)=>({...l,slug:l.topic+'-lesson-'+(i+1),kind:'lesson',position:i})),...content.questions.map((q,i)=>({...q,topic:'questionnaire',slug:'question-'+(i+1),kind:'question',position:i})),...content.diagrams.map(d=>({...d,slug:d.topic,kind:'diagram',position:0}))];
 for(const record of records){if(!(await db('portal_learning_items').where({slug:record.slug}).first()))await db('portal_learning_items').insert({...record,data:record.data?JSON.stringify(record.data):null});}
};
exports.down=async()=>{throw new Error('Portal records are forward-only. Restore a reviewed backup rather than discarding people data.');};
