'use strict';
const lessons = [
 {topic:'angular',title:'Small components, clear responsibilities',body:'A component pairs a view with the behavior that view needs. Keep a people card focused on displaying a person, and let a directory page handle fetching and filtering. Inputs carry data into the card; outputs report user actions to its parent. This project uses Angular 10 NgModules and decorator-based inputs, so examples from newer Angular documentation may need adaptation.',example:'@Input() employee: Employee;\n@Output() selected = new EventEmitter<Employee>();\n\nselectPerson() {\n  this.selected.emit(this.employee);\n}',source:'https://angular.dev/guide/components/inputs',minutes:4},
 {topic:'angular',title:'Share data through services',body:'Dependency injection gives components access to shared services. Put API calls in a service and keep loading, error, and empty states in the view. When subscribing to a long-lived stream such as route parameters, unsubscribe when the component is destroyed. Never assume a JSON field is already parsed: normalize it at the API boundary.',example:'constructor(private people: PeopleService) {}\n\nload() {\n  this.loading = true;\n  this.people.list().subscribe(\n    data => { this.peopleList = data; this.loading = false; },\n    error => { this.error = error.message; this.loading = false; }\n  );\n}',source:'https://angular.dev/guide/di',minutes:5},
 {topic:'node',title:'Keep the event loop moving',body:'Node.js handles many I/O operations without blocking JavaScript execution while waiting for the result. Await asynchronous database calls rather than blocking the event loop. CPU-heavy transformations still take processing time; split large work into bounded jobs or move it to a worker. In an API, validate first, perform the operation, and send one response.',example:'router.get("/people", async (req, res, next) => {\n  try {\n    const people = await db("employees").limit(20);\n    res.json({ data: people });\n  } catch (error) {\n    next(error);\n  }\n});',source:'https://nodejs.org/en/learn/asynchronous-work/dont-block-the-event-loop',minutes:4},
 {topic:'node',title:'Trust the server, validate the boundary',body:'A browser can suggest an action, but the server decides whether the user may perform it. Verify the session, derive the actor from that session, validate allowed fields, and use bound query parameters. Never trust a submitted role or createdBy value. Return useful errors without returning passwords, tokens, or internal SQL.',example:'const actor = req.user;\nif (!actor.permissions.includes("employees:write")) {\n  return res.status(403).json({ message: "Access denied" });\n}\nconst name = String(req.body.firstName || "").trim();\nif (!name) return res.status(400).json({ message: "Name is required" });',source:'https://nodejs.org/en/learn/asynchronous-work/dont-block-the-event-loop',minutes:4},
 {topic:'mysql',title:'Model a relationship, not a restriction',body:'Use a primary key to identify each row and a foreign key to describe a relationship between tables. An employee can have many attendance events: index the employee ID, but do not make it unique in an event table. Use a unique employee ID only when the model truly allows one related row, such as one basic-details record per employee.',example:'CREATE TABLE attendance_example (\n  id INT PRIMARY KEY AUTO_INCREMENT,\n  employee_id INT NOT NULL,\n  arrived_at DATETIME NOT NULL,\n  INDEX (employee_id),\n  FOREIGN KEY (employee_id) REFERENCES employees(userId)\n);',source:'https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html',minutes:5},
 {topic:'mysql',title:'Change related records together',body:'A transaction groups related changes so they can commit together or roll back on failure. Creating an employee account and its login should be one unit of work. Schema changes are different: many MySQL DDL statements implicitly commit, so migrations must be designed for recovery and tested against existing data.',example:'await db.transaction(async trx => {\n  const [id] = await trx("employees").insert(employee);\n  await trx("employee_login").insert({\n    ...login, createdBy: id\n  });\n});',source:'https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html',minutes:4},
 {topic:'mongodb',title:'Start with how the data is used',body:'MongoDB documents can embed related data or reference other documents. Embed information that belongs together and is usually read together, such as an address on an employee profile. Use references when related records are shared, independently managed, or can grow without a useful bound. Model the access pattern rather than copying relational tables mechanically.',example:'{\n  employeeId: "EMP042",\n  name: { first: "Asha", last: "Rao" },\n  address: { city: "Pune", country: "India" },\n  departmentId: ObjectId("507f1f77bcf86cd799439011")\n}',source:'https://www.mongodb.com/docs/manual/data-modeling/embedding/',minutes:4},
 {topic:'mongodb',title:'Make boundaries explicit',body:'Schema flexibility does not mean that every shape is equally useful. Decide which fields are required, how identifiers are represented, and which values the application accepts. Keep high-growth event histories separate from the employee document when an unbounded embedded array would make updates and reads harder to manage. This HRMS stores its operational data in MySQL; these lessons do not require a MongoDB server.',example:'// An event references an employee rather than expanding their profile.\n{ employeeId: "EMP042", event: "clock-in", at: ISODate("2026-09-19T03:30:00Z") }',source:'https://www.mongodb.com/docs/manual/data-modeling/schema-design-process/map-relationships/',minutes:4}
];
const questions=[
 {title:'Which layer must enforce permission to update an employee?',data:{options:['The button visibility in the browser','The authenticated API on the server','The CSS class on the form'],correctIndex:1,explanation:'The server must verify the authenticated actor and permission. Hiding a button is a usability choice, not authorization.'}},
 {title:'How should attendance events relate to an employee?',data:{options:['One event per employee, enforced by a unique employee ID','Many events with an indexed foreign key','No employee identifier is needed'],correctIndex:1,explanation:'Attendance is a history. An indexed, non-unique foreign key supports multiple events for each employee.'}},
 {title:'What is the purpose of an Angular service in this portal?',data:{options:['Share API and business logic between components','Replace the database','Store all passwords in the browser'],correctIndex:0,explanation:'Services keep shared behavior and API access separate from presentation components.'}},
 {title:'When is embedding a good starting point in MongoDB?',data:{options:['For every event that will ever happen','For related, bounded data commonly read together','Only when there is no identifier'],correctIndex:1,explanation:'Embedding is useful for related data commonly read together, while unbounded histories often belong in separate collections.'}}
];
const diagrams=[
 {topic:'workflows',title:'Workflow diagrams',body:'Follow the actual request review flow implemented in this workspace.',data:{caption:'A request is stored first. Only an authorized reviewer can make the final decision. The original requester receives an in-app update.',nodes:[{tag:'01 · EMPLOYEE',title:'Submit a request',description:'Choose a category, add context, and submit.'},{tag:'02 · DATABASE',title:'Pending review',description:'The request is saved with its owner and timestamps.'},{tag:'03 · REVIEWER',title:'Review the context',description:'An authorized reviewer checks the details.'},{tag:'04 · DECISION',title:'Approve or decline',description:'A pending request moves to one final decision.'},{tag:'05 · NOTIFICATION',title:'Close the loop',description:'An in-app notification records the outcome.'}],edges:[{from:'Submit',to:'Pending',label:'Saved to portal_requests'},{from:'Pending',to:'Review',label:'requests:review permission'},{from:'Review',to:'Decision',label:'Atomic state change'},{from:'Decision',to:'Notification',label:'Visible to the requester'}]}},
 {topic:'relationships',title:'Relationship diagrams',body:'Understand the core HRMS data model and the new portal tables.',data:{caption:'Solid relationships below correspond to database foreign keys. Onboarding identifies the subject employee inside employeeInfo JSON, while approvedBy is a relational foreign key.',nodes:[{tag:'CORE · IDENTITY',title:'employees',fields:['PK userId','UNIQUE empId','UNIQUE userName','UNIQUE email']},{tag:'ONE TO ONE',title:'employee_basic_details',fields:['PK empBasicDetailId','FK empId → employees.empId','studyInfo / familyInfo']},{tag:'ONE TO MANY',title:'employee_attendance_details',fields:['PK empAttendDetailId','FK empId → employees.empId','loginTime / logoutTime']},{tag:'WORKSPACE',title:'portal_requests',fields:['PK id','FK userId → employees.userId','kind / status / description']},{tag:'LEARNING',title:'portal_learning_progress',fields:['FK userId → employees.userId','FK itemId → portal_learning_items.id','UNIQUE userId + itemId']},{tag:'SECURITY',title:'portal_sessions',fields:['PK id','FK userId → employees.userId','expiresAt / revokedAt']}],edges:[{from:'employees',to:'basic details',label:'1 : 0..1'},{from:'employees',to:'attendance events',label:'1 : many'},{from:'employees',to:'requests',label:'1 : many'},{from:'employees',to:'learning progress',label:'1 : many'},{from:'learning items',to:'learning progress',label:'1 : many'},{from:'employees',to:'sessions',label:'1 : many'}]}}
];
module.exports={lessons,questions,diagrams};
